//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagerService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskTable
    {
        public int TaskId { get; set; }
        public string ProjectName { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string TaskName { get; set; }
        public Nullable<int> Priority { get; set; }
        public string ParentTask { get; set; }
        public Nullable<bool> IsParent { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> UserId { get; set; }
        public string UserName { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string Status { get; set; }
    
        public virtual ProjectTable ProjectTable { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
